CREATE TABLE UGYFEL_MASZKOLT (
    LOGIN_MASZKOLT NVARCHAR(255) MASKED WITH (FUNCTION = 'default()'),
    EMAIL_MASZKOLT NVARCHAR(255) MASKED WITH (FUNCTION = 'email()'),
    NEV_MASZKOLT NVARCHAR(255) MASKED WITH (FUNCTION = 'partial(1,"XXX",2)'),
    SZULEV_MASZKOLT INT MASKED WITH (FUNCTION = 'random(1950,2000)'),
    NEM NVARCHAR(255), /*NVARCHAR(1) lenne, de az eredeti UGYFEL tabla 102. sorába hiba van, így nem lehet*/
    CIM_MASZKOLT NVARCHAR(255) MASKED WITH (FUNCTION = 'default()')
);

INSERT INTO UGYFEL_MASZKOLT (LOGIN_MASZKOLT, EMAIL_MASZKOLT, NEV_MASZKOLT, SZULEV_MASZKOLT, NEM, CIM_MASZKOLT)
SELECT
  [LOGIN],
  EMAIL,
  NEV,
  SZULEV,
  NEM,
  CIM
FROM UGYFEL;

CREATE USER MaskUser12 WITHOUT LOGIN;

GRANT SELECT ON UGYFEL_MASZKOLT TO MaskUser12;

EXECUTE AS USER = 'MaskUser12';
SELECT * FROM UGYFEL_MASZKOLT;
REVERT;
